config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registerations: "registerations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :hospital do
    resources :treatment do
      resources :price
    end
  end

  resources :request

  get '/hospital/:hospital_id/treatment/:id/user/:uid', to: "treatment#assignuser"
  patch '/hospital/:hospital_id/treatment/:id/price', controller: 'price', action: :create

end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :users, optional:true

  enum statusd: [:pending, :reject, :accept ]

   #validation here
   validates :user_id, presence: true # must present
 
end

app/controllers/request_controller.rb
class RequestController < ApplicationController
    load_and_authorize_resource only: [:index, :new, :show, :edit]

    def index
        @docreq = Request.where(requestto:current_user.id)
        @patreq = Request.where(user_id:current_user.id)
    end
    def show
        @req = Request.find(params[:id])
    end
    def new
        @req = current_user.requests.new
    end
    def create
        @req = current_user.requests.create(req_params_create)
        @req.update(status:1)

        if @req.save
            redirect_to request_index_path, :notice => "new req added"
        else
            render "new"
        end
    end
    def edit
        @req = Request.find(params[:id])
    end
    def update
        if params[:request][:status] == "accept"
            @s = 3
        elsif params[:request][:status] == "reject"
            @s=2
        else params[:request][:status] == "pending"
            @s= 1

        end
        @req = Request.find(params[:id]).update!(status:@s)

        redirect_to request_index_path, :notice => "req status added"
    end
    def destroy
        @req = Request.destroy(params[:id])
        redirect_to request_index_path, :notice => "req is deleted"
    end

    private
    def req_params
        params.require(:request).permit(:user_id, :requestto, :status)
    end
    def req_params_create
        params.permit(:user_id, :requestto, :status)
    end
end
  

app/views/request/edit.html.erb
<h6><u> edit request status </u></h6>

<%= form_for @req,:url => { :action => "update" } do |f| %>
    <%= token_tag %>
    <p>
        <%= f.label :status %> <br/>
        <%= f.select :status, Request.statusds.keys %>
    </p>
  
    <p>
        <%= f.submit "update status" %>
    </p>

<% end %>

app/views/request/index.html.erb
<h6><u> Your Requests</u></h6>
<% if can? :create, Request %>
  <%= link_to "Add new request", new_request_path %>
<% end %>
<br>

<table class="table mx-5">
<thead>
  <tr>
    <th>Requested By (patient)</th>
    <th>Request To(doc) </th>
    <th>Status</th>
    <th></th>
  </tr>
</thead>
<tbody>

    <% if current_user.usertype == "patient" %>
      (patient see his req only)

      <% Request.where(user_id:current_user.id).each do |r| %>
        <tr>
          <td><%= User.find(r.user_id).name %>  </td>
          <td><%= User.find(r.requestto).name %> </td>
          <td>
              <% if r.status == 1 %> 
                pending
              <% elsif r.status == 2 %>
                rejected
              <% elsif r.status == 3 %>
                accepted
              <% end %>
          </td>
          <td> 
              <% if can? :update, Request %>
                <%= link_to "edit status", edit_request_path(r) %>
              <% end %>
          </td>
          <td> 
            <% if can? :destroy, Request %>
              <%= link_to "delete", r, :confirm => "are you sure?", :method => :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>   
    <% elsif current_user.usertype =="doctor" %>
      (doc see his req only)

      <% @docreq.all.each do |r| %>
        <tr>
          <td><%= User.find(r.user_id).name %>  </td>
          <td><%= User.find(r.requestto).name %> </td>
          <td>
            <% if r.status == 1 %> 
              pending
            <% elsif r.status == 2 %>
              rejected
            <% elsif r.status == 3 %>
              accepted
            <% end %>
          </td>
          <td> 
            <% if can? :update, Request %>
              <%= link_to "edit status", edit_request_path(r) %>
            <% end %>
          </td>
          <td> 
            <% if can? :destroy, Request %>
              <%= link_to "delete", r, :confirm => "are you sure?", :method => :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% elsif current_user.usertype =="admin"  %>
        Admin can see all request
      <% Request.all.each do |r| %>
        <tr>
          <td><%= User.find(r.user_id).name %>  </td>
          <td><%= User.find(r.requestto).name %> </td>
         <td>
            <% if r.status == 1 %> 
              pending
            <% elsif r.status == 2 %>
              rejected
            <% elsif r.status == 3 %>
              accepted
            <% end %>
          </td>
          <td> 
            <% if can? :update, Request %>
              <%= link_to "edit status", edit_request_path(r) %>
           <% end %>
          </td>
          <td> 
            <% if can? :destroy, Request %>
              <%= link_to "delete", r, :confirm => "are you sure?", :method => :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
</tbody>
</table>

app/views/request/new.html.erb
<h6><u> Create new Request to Following doctors for treatment </u></h6>

<%= form_for @req,:url => { :action => "create" } do |f| %>
<table class="table">
 <thead>
   <tr>
     <th>Doctor Name</th>
     <th>Email </th>
   </tr>
 </thead>
 <tbody>
  <%  User.all.each do |u| %>
  <% if u.usertype =="doctor" %>
  <tr> 
    <td><%= u.name %> </td>
    <td><%= u.email %> </td>
    <td><%= check_box_tag "requestto", u.id, nil, {multiple:false} %></td>
  </tr>
  <% end %>
  <% end %>
 </tbody>
 </table>

<p>
<%= f.submit "create req" %>
</p>
<% end %>

app/views/request/show.html.erb
<u>request by <%= User.find(@req.user_id).name %></u>
<p> 
<p> created at = <%= @req.created_at %></p>
<p> updated at = <%= @req.updated_at %></p>
<br>