config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registerations: "registerations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :hospital do
    resources :treatment do
      resources :price
    end
  end

  resources :request

  get '/hospital/:hospital_id/treatment/:id/user/:uid', to: "treatment#assignuser"
  patch '/hospital/:hospital_id/treatment/:id/price', controller: 'price', action: :create

end

app/models/hospital.rb
class Hospital < ApplicationRecord
    has_many :hospitaltreatments, dependent: :delete_all
    has_many :treatments, through: :hospitaltreatments
    accepts_nested_attributes_for :treatments


     #validation here
     validates :name, :city, presence: true
     validates :address, length: { minimum: 5 }
     validates :name, uniqueness: { case_sensitive: false }


end

app/controllers/hospital_controller.rb
class HospitalController < ApplicationController
    # load_and_authorize_resource
    load_and_authorize_resource only: [:index, :show, :new, :edit]

    def index
        @myhos = Hospital.all
    end
    def show
        @onehos = Hospital.find(params[:id])
    end
    def new
        @hos = Hospital.new
    end
    def create
        # @hos = Hospital.create!(name:params[:hospital][:name], city:params[:hospital][:city], address:params[:hospital][:address])
        @hos = Hospital.create!(hos_params)
       
        if @hos.save
            redirect_to hospital_index_path, :notice => "new hospital added"
        else
            render "new"
        end
    end
    def edit
        @hos = Hospital.find(params[:id])
    end
    def update
        @hos = Hospital.find(params[:id])
        # @uid = params[:user_ids]
        #adding manager id to aray
        # @uid.append(current_user.id)
        @hos.update(hos_params)

        redirect_to hospital_index_path, :notice => "hospital is edited"
    end
    def destroy
        @hos = Hospital.destroy(params[:id])
        redirect_to hospital_index_path, :notice => "hospital is deleted"
    end

    private
    def hos_params
        params.require(:hospital).permit(:name, :city, :address)
    end
end
  

app/views/hospital/edit.html.erb
<div class="m-5">
        <h2><u>Update Hospital </u></h2>

        <%= form_for @hos,:url => { :action => "update" } do |f| %>
            <%= token_tag %>
            <% if @hos.errors.any? %>
                <h6> error = </h6>
                <%= @hos.errors.full_messages.each do |m| %>
                <%= m %><br>
                <% end %>
            <% end %>
            <p>
                <%= f.label :name %> <br/>
                <%= f.text_field :name %>
            </p>
            <p>
                <%= f.label :city %> <br/>
                <%= f.text_field :city %>
            </p>
            <p>
                <%= f.label :address %> <br/>
                <%= f.text_field :address %>
            </p>
            <p>
                <%= f.submit "update hospital" %>
            </p>
        <% end %>

</div>

app/views/hospital/index.html.erb
<table class="table">
<h2><u>All Hospitals</u></h2> 
<% if can? :destroy, @myhos %>

<%= link_to "Add new Hospital", new_hospital_path %>
<% end %>
<br>
<thead>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Address</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @myhos.each do |x| %>
    <tr>
        <td> <%= link_to x.name, x %>  </td>
        <td> <%= x.city %></td>
        <td> <%= x.address %>  </td>
        <td>
          <% if can? :destroy, @myhos %>
            <%= link_to "delete", x, :confirm => "are you sure?", :method => :delete %>
          <% end %>
        </td>
        <td>
          <% if can? :update, @myhos %>

            <%= link_to "update", edit_hospital_path(x) %>
          <% end %>
        </td>

    </tr>
<% end %>

</tbody>
</table>

app/views/hospital/new.html.erb
<div class="m-5">
        <h2><u>Create a New Hospital </u></h2>

        <%= form_for @hos,:url => { :action => "create" } do |f| %>
            <%= token_tag %>
            <% if @hos.errors.any? %>
                <h6> error = </h6>
                <%= @hos.errors.full_messages.each do |m| %>
                <%= m %><br>
                <% end %>
            <% end %>
            <p>
                <%= f.label :name %> <br/>
                <%= f.text_field :name %>
            </p>
            <p>
                <%= f.label :city %> <br/>
                <%= f.text_field :city %>
            </p>
            <p>
                <%= f.label :address %> <br/>
                <%= f.text_field :address %>
            </p>

            <p>
                <%= f.submit "create new hospital" %>
            </p>
        <% end %>

</div>

app/views/hospital/show.html.erb
<div class="p-4">
<h1>Hospital Detail </h1>
<p>name = <%= @onehos.name %></p>
<p>city = <%= @onehos.city %></p>
<p> address = <%= @onehos.address %></p>
<p> created at = <%= @onehos.created_at %></p>
<p> updated at = <%= @onehos.updated_at %></p>
<br>

<h6>Hospital has following doctors</h6>
<% @onehos.hospitaltreatments.each do |ht| %>
    <% User.where(hospitaltreatment_id:ht.id).each do |u| %>
        <% if u.usertype == "doctor" %>
            <p> <%= u.name %> </p>
        <% end %>
    <% end %>
<% end %>

<%= link_to "see treatments", hospital_treatment_index_path(@onehos) %><br>




</div>