config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registerations: "registerations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  resources :hospital do
    resources :treatment do
      resources :price
    end
  end

  resources :request

  get '/hospital/:hospital_id/treatment/:id/user/:uid', to: "treatment#assignuser"
  patch '/hospital/:hospital_id/treatment/:id/price', controller: 'price', action: :create

end

app/models/treatment.rb
class Treatment < ApplicationRecord
    has_many :hospitaltreatments, dependent: :delete_all
    has_many :hospitals, through: :hospitaltreatments
    accepts_nested_attributes_for :hospitals

    validates :name, presence: true

end

app/controllers/treatment_controller.rb
class TreatmentController < ApplicationController
    # load_and_authorize_resource
    load_and_authorize_resource only: [:index, :show, :new, :edit]

    def index
        @mytreat = Hospital.find(params[:hospital_id]).treatments.all
    end
    def show
        @onetreat = Treatment.find(params[:id])
    end
    def new
        @treat = Hospital.find(params[:hospital_id]).treatments.new
    end

    def assignuser
        @ht= Hospitaltreatment.find_by(hospital_id:params[:hospital_id], treatment_id: params[:id]).id

        if User.find(params[:uid]).hospitaltreatment_id == nil
           a= true;
            User.all.each do |u|
                if u.hospitaltreatment_id == @ht
                    a= false
                end 
            end
            if a
                User.find(params[:uid]).update(hospitaltreatment_id:@ht)
                redirect_to hospital_treatment_path, :notice => "user is assigned"
            else
                redirect_to hospital_treatment_path, :notice => "not more than one user"
            end

        elsif User.find(params[:uid]).hospitaltreatment_id != nil
            User.find(params[:uid]).update(hospitaltreatment_id:nil)
            redirect_to hospital_treatment_path, :notice => "user is removed"
        end
    end
    def assignprice
        @ht= Hospitaltreatment.find_by(hospital_id:params[:hospital_id], treatment_id: params[:id])
        @ht.update(price:params[:p])
        redirect_to hospital_treatment_path, :notice => "price assigned"
    end

    def create
        @treat = Hospital.find(params[:hospital_id]).treatments.create(treat_params)

        if @treat.save
            redirect_to hospital_treatment_index_path, :notice => "new Treatment added"
        else
            render "new"
        end
    end
    def edit
        @treat = Hospital.find(params[:hospital_id]).treatments.find(params[:id])
    end
    def update
        @treat = Hospital.find(params[:hospital_id]).treatments.find(params[:id])

        #adding manager id to aray
        # @uid.append(current_user.id)
        @treat.update(treat_params)

        redirect_to hospital_treatment_index_path, :notice => "Treatment is edited"
    end
    def destroy
        @treat = Treatment.destroy(params[:id])
        redirect_to hospital_treatment_index_path, :notice => "Treatment is deleted"
    end

    private
    def treat_params
        params.require(:treatment).permit(:name)
    end
end
  

app/views/treatment/assignuser.html.erb
<h3>assigned </h3>

app/views/treatment/edit.html.erb
<div class="m-5">
        <h2><u>Update Treatment </u></h2>

        <%= form_for @treat, :url => { :action => "update" } do |f| %>
            <%= token_tag %>
            <% if @treat.errors.any? %>
                <h6> error = </h6>
                <%= @treat.errors.full_messages.each do |m| %>
                <%= m %><br>
                <% end %>
            <% end %>
            <p>
                <%= f.label :name %> <br/>
                <%= f.text_field :name %>
            </p>
           

            <p>
                <%= f.submit "update treatment" %>
            </p>
        <% end %>

</div>

app/views/treatment/index.html.erb
<table class="table">
<h2><u>All Treatments</u></h2> 
<% if can? :create, @Treatment %>

<%= link_to "Add new Treatments", new_hospital_treatment_path %>
<% end %>

<br>
<thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @mytreat.each do |x| %>
    <tr>
      <td><a href="treatment/<%= x.id %>"><%= x.name %></a></td>
      
      <td> 
        <% if can? :update, @Treatment %>
          <a href="treatment/<%= x.id %>/edit">edit </a> 
        <% end %>
      </td>
      <td> 
        <% if can? :destroy, @Treatment %>
          <%= link_to 'Delete', hospital_treatment_path(params[:hospital_id], x), method: :delete, data: {confirm: 'Are you sure?'} %>  
        <% end %>
      </td>

    </tr>
<% end %>

</tbody>
</table>

app/views/treatment/new.html.erb
<div class="m-5">
        <h2><u>Create a New Treatment </u></h2>

        <%= form_for @treat,:url => { :action => "create" } do |f| %>
            <%= token_tag %>
            <% if @treat.errors.any? %>
                <h6> error = </h6>
                <%= @treat.errors.full_messages.each do |m| %>
                <%= m %><br>
                <% end %>
            <% end %>
            <p>
                <%= f.label :name %> <br/>
                <%= f.text_field :name %>
            </p>
            <p>
                <%= f.submit "create treatment" %>
            </p>
        <% end %>

</div>

app/views/treatment/show.html.erb
<div class="p-4">
<h1>Treatment Detail </h1>
<p>Name = <%= @onetreat.name %></p>
<p>
    Price = $ <%= Hospitaltreatment.find_by(hospital_id:params[:hospital_id], treatment_id: params[:id]).price %> 
    <% if can? :update, @Treatment %>
        <a href="/hospital/<%= params[:hospital_id] %>/treatment/<%= params[:id] %>/price/new">assign price </a>
    <% else %>
       ( you cannot assign price)
    <% end %>
</p>
<p> created at = <%= @onetreat.created_at %></p>
<p> updated at = <%= @onetreat.updated_at %></p>
<br>
<hr>

<div class="row">
<section class="col-6">
<h5>Already assigned doctors<h5>
<% User.all.each do |users| %>
    <% if users.usertype == "doctor" %>
    <% if users.hospitaltreatment_id == Hospitaltreatment.find_by(hospital_id:params[:hospital_id], treatment_id: params[:id]).id %>
        <p>  
            <%= users.name%>  
            <a href="/hospital/<%= params[:hospital_id] %>/treatment/<%= params[:id] %>/user/<%= users.id %>">unassign </a>
        </p>
    <% end %>
    <% end %>
<% end %>
</section>

<section class="col-6">
<h5>click to assign </h5>
<% User.all.each do |users| %>
    <% if users.usertype == "doctor" %>
    <% if users.hospitaltreatment_id == nil %>
    <p> 
        <%=users.name%>
        <a href="/hospital/<%= params[:hospital_id] %>/treatment/<%= params[:id] %>/user/<%= users.id %>">assign </a>
    </p>
    <% end %>
    <% end %>
<% end %>
</section>
<div>
</div>